declare module 'slash2';
declare module '*.css';
declare module '*.less';
declare module '*.scss';
declare module '*.sass';
declare module '*.svg';
declare module '*.png';
declare module '*.jpg';
declare module '*.jpeg';
declare module '*.gif';
declare module '*.bmp';
declare module '*.tiff';
declare module 'omit.js';
declare module 'numeral';
declare module 'mockjs';

declare const __MYAPP_WEB_DEV_LOGIN_USERNAME__: string;
declare const __MYAPP_WEB_DEV_LOGIN_PASSWORD__: string;
declare const __MYAPP_WEB_PROXY_TARGET__: string;
declare const __MYAPP_WEB_API_BASE_URL__: string;
declare const __MYAPP_WEB_ENABLE_WATERMARK__: boolean;
